theme: jekyll-theme-dinky
title: Amar Junankar
description: Software Development Knowledge Base
permalink: /:categories/:title:output_ext

kramdown:
  syntax_highlighter_opts:
    default_lang: cpp
    style: vs
    
collections:
  cplusplus:
    output: true
  software_design:
    output: true
  software_testing:
    output: true
  soft_skills:
    output: true
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
    